import Head from "next/head";
import styles from "../styles/Home.module.css";
import ChooicePand from "../views/ChooicePand";

const Home = (props) => {
  return (
    <div className={styles.container}>
      <Head>
        <title>Cours Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className={styles.main}>
        <div>
          <h1>Cours Next-App</h1>
        </div>
        <ChooicePand />
      </main>

      <footer className={styles.footer}></footer>
    </div>
  );
};
// 此函数在构建时被调用
export async function getStaticProps(context) {
  // const res = await fetch("https://.../posts");
  // const posts = await res.json();
  /*返回给Index组件作为入口参数 服务端代理数据请求
    组件则负责将数据渲染出来 返回给客户端HTML
  */
  //const { params } = context;
  //重定向
  return {
    redirect: {
      destination: "/user/analysis",
      permanent: false,
    },
  };
  // return {
  //   props: {
  //     id: "HELLO NEXT",
  //     runtimeId: params.id,
  //   },
  //   // notFound:true 返回404 not found page
  //   revalidate: 10,
  //   //增量静态重新生成 (ISR) 使您能够在每页的基础上使用静态生成，而无需重建整个站点 In seconds
  //   //没有被预渲染的配和fallback将会被渲染 则会产生缓存 缓存时间为10s
  // };
}
export default Home;
